version: '3'

services:
  bettor-league-elasticsearch:
    container_name: bettor-league-elasticsearch
    build: ./elasticsearch/
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - node.name=node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - transport.tcp.port=9300
      - transport.publish_port=9300
      - discovery.type=single-node
      - cluster.name=bettor-league-cluster
      - bootstrap.memory_lock=true
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.enabled=false
      - xpack.security.transport.filter.allow=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - bettor-league-network
      - default
    labels:
      - "traefik.backend=bettor-league-elasticsearch"
      - "traefik.docker.network=bettor-league-network"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:elastic.bettorleague.ovh"
      - "traefik.port=9200"

  bettor-league-kibana:
    container_name: bettor-league-kibana
    build: ./kibana/
    restart: always
    ports:
      - "5601:5601"
    links:
      - bettor-league-elasticsearch:elasticsearch
    networks:
      - bettor-league-network
      - default
    labels:
      - "traefik.backend=bettor-league-kibana"
      - "traefik.docker.network=bettor-league-network"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:kibana.bettorleague.ovh"
      - "traefik.port=5601"

  bettor-league-logstash:
    container_name: bettor-league-logstash
    build: ./logstash/
    restart: always
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "9999:9999"
    links:
      - bettor-league-elasticsearch:elasticsearch
    networks:
      - bettor-league-network
      - default
    labels:
      - "traefik.backend=bettor-league-logstash"
      - "traefik.docker.network=bettor-league-network"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:logstash.bettorleague.ovh"
      - "traefik.port=9999"

networks:
  bettor-league-network:
    external: true

